language: python
matrix:
  include:
    - python: 3.6.8
      dist: xenial
      sudo: true
before_install:
    - pip install --upgrade setuptools pip
    - pip install -r requirements/test.txt
script:
  - coverage run --source='.' manage.py test -v2
after_success:
  - coveralls