version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./staticfiles:/app/static/:ro
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']

  mailhog:
      image: mailhog/mailhog:latest
      ports:
          - "8025:8025"

  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    tty: true
    restart: always
    depends_on:
      - mysql_db
      - nginx
      - mailhog
    volumes:
      - ./staticfiles:/app/static/
    environment:
      - DJANGO_SETTINGS_MODULE=helpecBackend.settings.production
      - DATABASE_NAME=helpec
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      # - SENTRY_ENABLE=1
      - SENTRY_DJANGO_DSN=""
      - EMAIL_HOST_USER=""
      - EMAIL_HOST_PASSWORD=""
      - ALLOWED_HOSTS=""
