version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./staticfiles:/app/static/:ro
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']

  mailhog:
      image: mailhog/mailhog:latest
      ports:
          - "8025:8025"

  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    tty: true
    restart: always
    depends_on:
      - mysql_db
      - nginx
      - mailhog
    volumes:
      - ./staticfiles:/app/static/
